### ISSUE TITLE
Any plan to support golang plugins?

### ISSUE THREAD

**Issue by vnalawad-tibco** [GoogleCloudPlatform/functions-framework-go#105]
I have a case where I would like to build a golang plugin (linux) locally and run it in Google Cloud Functions. I attempted same but ran into package version mismatch issue.
Also, would it be possible to run golang binary in Google Cloud Function?

**Comment by grant** [comment]
Hi Vijay,
I don't recommend using Cloud Functions running binaries within the function, but it may be possible.

Functions run on ubuntu 18.

Can you describe the specific issue with the Functions Framework, including steps to reproduce the issue?

**Comment by anniefu** [comment]
GCF contract is a function rather than a binary. The Functions Framework is not going to support Golang plugins at this time. 

You may be able to package your binary into a Docker container and running on Cloud Run though.
