### ISSUE TITLE
Document revised `main()` for declarative functions

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/functions-framework-go#106]
Declarative functions include a new registration mechanism on init(). This leads to a change in how the main.go should be arranged for running the code outside the context of Cloud Functions.

This is what I put together:

```
package main

import (
	"log"
	"os"

	"github.com/GoogleCloudPlatform/functions-framework-go/funcframework"
	_ "grayside.example.com"
)

func main() {
	// Use PORT environment variable, or default to 8080.
	port := "8080"
	if envPort := os.Getenv("PORT"); envPort != "" {
		port = envPort
	}
	if err := funcframework.Start(port); err != nil {
		log.Fatalf("funcframework.Start: %v\n", err)
	}
}
```

1. Removes the handling registration from main(), that is now handled inside funcframework.Start
2. Adds a package import for the parent package, where my function lives.

**Comment by anniefu** [comment]
Documented with #118
