### ISSUE TITLE
Add empty registry error on funcframework.Start

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/functions-framework-go#107]
## Problem

When assembling a main() for your function, such as to run it locally or in a Cloud Run container, if any mistakes are made in registering your function the framework server reports requests as 404 without explanation.

Examples of mistakes can be simply forgetting an import statement, something I did in the course of working out my `main()` in #106.

## Expected

If the registry is empty, instead of starting up a no-op HTTP server the functions framework should log an error, possibly fatal.

**Comment by codyoss** [comment]
I agree, I think this should be fatal as it was not the intention of the user.
