### ISSUE TITLE
Approach/usage with Firebase HTTPS callable Cloud Functions and JWT

### ISSUE THREAD

**Issue by caprica** [GoogleCloudPlatform/functions-framework-go#113]
I have a question around the scope of this project and what the framework provides.

I am implementing cloud functions using go, and using the Firebase client SDK to invoke those functions via httpsCallable from web and mobile clients. This is working so far. Now I need to do this with OAuth.

From what I can tell, this framework does not offer any assistance with the Cloud Function HTTPS callable "protocol" does it? It does not do any automatic validation of a Bearer token, or make the JWT available in the request context, wrap the response with data/error attributes or anything like that? I am supposed to implement that in my cloud function? I am currently using the Firebase Admin SDK in my cloud function and bespoke code to do just that.

I am trying to understand if I'm using this framework in the right way, or if I've missed something.

**Comment by anniefu** [comment]
Hello, thanks for using functions framework! You are correct, the framework does not offer assistance with bearer tokens or authentication. You do have full access to the HTTP request and response with HTTP functions.

We are not planning on adding any capabilities directly into the framework to help with OAuth. You may be able to find an existing library to help with that though: https://github.com/golang-jwt/jwt#jwt-go
