### ISSUE TITLE
readme out of date following breaking change in #99

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/functions-framework-go#114]
A couple of methods were moved to a new package in this PR. As this was a documented and released way of using the framework I think these functions should be restored to the old package. The new ones can exists but so can the old ones. They can be deprecated and even just call the new methods if needed.

https://github.com/GoogleCloudPlatform/functions-framework-go#declarative-functions

**Comment by codyoss** [comment]
cc @grant

**Comment by codyoss** [comment]
I think it is correct and fine to update the README to use the new package. But #99 did introduce breaking changes that [removed previously public](https://pkg.go.dev/github.com/GoogleCloudPlatform/functions-framework-go@v1.4.0/funcframework#CloudEvent) APIs in a minor version. To limit code breakage it might be a good to reinstate these methods and just deprecate them until a v2 of this library comes out.

**Comment by anniefu** [comment]
`v1.4.0` was a bad release of Functions Framework that was incompatible with GCF. We can redact it if you like.

**Comment by codyoss** [comment]
> v1.4.0 was a bad release of Functions Framework that was incompatible with GCF. We can redact it if you like.

Ack. Yeah might be a good idea to pull that version if that is the case.

**Comment by anniefu** [comment]
I've deleted the release and tag from GitHub, though we can't use the Go `redact` feature because we run tests with versions < Go 1.15 which error if there's a `redact` clause in the `go.mod`.

**Comment by mstibbard** [comment]
The readme quickstart example does not work. I think the first 4 lines of `cmd/main.go`s `main()` were accidentally removed in the last commit?
```go
func main() {
	ctx := context.Background()
	if err := funcframework.RegisterHTTPFunctionContext(ctx, "/", function.HelloWorld); err != nil {
		log.Fatalf("funcframework.RegisterHTTPFunctionContext: %v\n", err)
	}
	// Use PORT environment variable, or default to 8080.
	port := "8080"
	if envPort := os.Getenv("PORT"); envPort != "" {
		port = envPort
	}
	if err := funcframework.Start(port); err != nil {
		log.Fatalf("funcframework.Start: %v\n", err)
	}
}
```

**Comment by ptiger10** [comment]
I think those lines were removed intentionally. You do not need to register your function again in the server as long as 1) it is registered in the file containing your cloud function, 2) the server opens that file, and 3) you provide the FUNCTION_TARGET env variable before launching the server.

I also struggled with this at first because I was copy/pasting the quickstart line `_ "example.com/hello"`. You need to change this to your module name + path to the file. So if your module name is "functions" and the file is in root, this should just be `_ "functions"`
