### ISSUE TITLE
vendoring deps became harder after #99 /w declarative syntax

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/functions-framework-go#115]
Before these functions were moved in #99 a person could easily vendor code with private dependencies and not make any changes to source. After this change however if you use the new package, vendor code, and deploy you get an error something like: `could not import .` where the "." related to the `funcframework` package.

This is because the Cloud Function needs the context of the framework package to start the http server. This can be remedied in user code by adding: `import _ "github.com/GoogleCloudPlatform/functions-framework-go/funcframework"`. But this does not seem ideal. This blanket import could also be added to the functions package, but this is very close to introducing an import cycle which Go does not allow. The current code builds but tests don't. The tests could likely be refactored though to avoid this.

@grant @anniefu

**Comment by anniefu** [comment]
Could you give a code example?

I would expect if you are using the new package, you already have a required import in your function code for "github.com/GoogleCloudPlatform/functions-framework-go/functions" and shouldn't need to blank import it.

**Comment by anniefu** [comment]
This is actually the officially documented behavior for the Go 1.16 runtime: https://cloud.google.com/functions/docs/concepts/go-runtime

The error message is worse though because the detection isn't quite advanced enough to differentiate between subpackages of the module. We can restore the previous error message to include the blank import.

**Comment by codyoss** [comment]
True, and this was always required for gen1 when vendoring, but before #99 users did not have to do this for gen2 with declarative syntax as the package they used to declare their function was the same required by Cloud Functions start up the function. If we can find a way to avoid having an empty import I think it would lead to a better user experience that is less error prone.

**Comment by codyoss** [comment]
Sounds good, I think it still might be a good idea to move the "_ import" into the functions package so users don't have to have to add it in their code. We can manage that bit of complexity for them and avoid the cycles.
