### ISSUE TITLE
PubSub message missing fields

### ISSUE THREAD

**Issue by caleb-artifact** [GoogleCloudPlatform/functions-framework-go#119]
**Summary**
The PubSub event is missing `DeliveryAttempt` and `OrderingKey`.

Compare
https://github.com/GoogleCloudPlatform/functions-framework-go/blob/fcae4db92cfc9c8cc54f6eb8f67a57a2c68de5b1/internal/events/pubsub/pubsub.go#L29-L46
to
https://github.com/googleapis/google-cloud-go/blob/c0e65c58430ba7e2f39a90c5e3c27f4f34f3e188/internal/pubsub/message.go#L50-L60

**Expected**
The `DeliveryAttempt` and `OrderingKeys` to exist on the PubSub message.

**Comment by caleb-artifact** [comment]
Hey @grant I noticed your previous fix added the fields to Message, but from digging around it looks like the fields are populated on the `LegacyPushSubscriptionEvent`.  I've tested the functionality in a fork of this repo and it's been working as expected.

**Comment by anniefu** [comment]
Hey Caleb, thanks for filing this issue!

Unfortunately, GCF actually does not pass through the `DeliveryAttempt` or `OrderingKeys` fields to the Functions Framework in production, so even if we were to fix the frameworks, those fields would be empty.

I'm going to close this bug because it's out of the hands of the frameworks.

**Comment by caleb-artifact** [comment]
@anniefu We're actually able to get those fields in our production app on GCP.

Here's the solution we're using:
https://github.com/caleb-artifact/functions-framework-go/commit/60db9330b9b812544dcda1ba29f13b2c27649f86

I think the important thing to notice is that the event is on the `LegacyPushSubscriptionEvent`.
With it we have been able to get the DeliveryAttempt to provide a better way to handle subscriptions with a maximum retry count.

If the field isn't in production then I'm confused as to why our solution has been working.
