### ISSUE TITLE
package "framework" not descriptive 

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-go#13]
# package "framework" not descriptive

As mentioned in the internal Go chat room, the package `framework` isn't really descriptive or clear.

Perhaps we can change the name to `funcframework` or something to discern this framework from other Go packages that are considered frameworks.

Ref: https://blog.golang.org/package-names

**Comment by juliehockett** [comment]
The new `funcframework` package exists now. Once that change is migrated internally, I'll remove the old package files.
