### ISSUE TITLE
Confluent Cloud

### ISSUE THREAD

**Issue by 1989shack** [GoogleCloudPlatform/functions-framework-go#148]
https://confluent.cloud/signup/idp/github?signup_source=iosocial&_ga=2.136384816.1651296864.1660258858-468307656.1660258858

**Comment by jama22** [comment]
@1989shack I've noticed that you've opened many issues that aren't related to functions-framework. Please refrain from sending us this spam. You can refer to our community code of conduct guidelines here https://opensource.google/conduct/ 

If you continue to create issues that are not relevant to the project we'll have to consider banning you
