### ISSUE TITLE
Upgrading to v1.6.0 breaks deployment to Docker Run or Cloud Run: Function failed to start: no matching function found with name: "EntryPoint"

### ISSUE THREAD

**Issue by BrunoReboul** [GoogleCloudPlatform/functions-framework-go#150]
TL~DR: docker images built using the pack command (Native Build Pack v0.27.0) and Function Framework v1.6.0 fail to initiate with `no matching function with name"EntryPoint"` while this function succeed to run a with local GO program. Reverting to v1.5.3 make it works again.

**To reproduce the Issue:**
Upgrading to v1.6.0 breaks deployment to Docker Run or Cloud Run with error: Function failed to start: no matching function found with name: "EntryPoint"

**Workarround**
revert to github.com/GoogleCloudPlatform/functions-framework-go v1.5.3

**Context**
- This issue is not specific to a given microservices, It impact [any microservices in Realtime Asset Monitor](https://gitlab.com/realtime-asset-monitor) that are updated to v1.6.0 
- The docker image is built using [Native Buildpack Pack command](https://buildpacks.io/docs/tools/pack/) v0.27.0
- Go v1.19
- The pack command succeed to build a docker image both locally or in the CI pipe
- The built docker image cannot be run (both using local docker run or hosted in Google Cloud Run): it fails to initiate with error message `Function failed to start: no matching function found with name: "EntryPoint"`
- Running the [EntryPoint GO function](https://gitlab.com/realtime-asset-monitor/execute/-/blob/main/cmd/main.go) locally works

**Comment by nickm4062** [comment]
Seeing the same thing with cloud functions gen 1 deployments

**Comment by BrunoReboul** [comment]
Thanks for the fix, works well with v1.6.1
