### ISSUE TITLE
Ethwork

### ISSUE THREAD

**Issue by 1989shack** [GoogleCloudPlatform/functions-framework-go#155]
Application: Google Play services
Package name: com.google.android.gms
Process: com.google.android.gms
UID: 10030
Version: 22.31.12 (110300-464716382)
Protocol: TCP (IPv6)
State: FIN_WAIT1
Local Address: 10.109.231.209:58828
Remote Address: 142.250.77.195:443
Hostname: par21s11-in-f14.1e100.net

**Comment by jama22** [comment]
@1989shack this information doesn't seem relevant to the functions-framework project. Closing issue for now, please reopen if you think this was done in error
