### ISSUE TITLE
Android Firebase, Cluodfare Google Cloud Hosting 

### ISSUE THREAD

**Issue by 1989shack** [GoogleCloudPlatform/functions-framework-go#160]
https://go.cloudplatformonline.com/ODA4LUdKVy0zMTQAAAGGuysRwsOQD2jqBM-LI0EgFFQfnBm64i5u-XpalbwzJm3UNmzui-M6Lfv6SAx7OqW4boTZnGk=

**Comment by Arinerron** [comment]
the link serves malware smh

**Comment by Arinerron** [comment]
![image](https://github.com/GoogleCloudPlatform/functions-framework-go/assets/3926753/2a6070cf-4dc5-429a-acde-1592d3f4b137)
they're also mailing this link out from a convincing/legitimate email address
