### ISSUE TITLE
Unable to Serve Multiple Functions

### ISSUE THREAD

**Issue by gvmorley** [GoogleCloudPlatform/functions-framework-go#166]
Hi,

I'm having issues using the Functions Framework when registering multiple functions.

The Framework only ever serves the last registered function.

As an example, I'm using this code to test:
```
package main

import (
	"context"
	"fmt"
	"github.com/GoogleCloudPlatform/functions-framework-go/funcframework"
	"log"
	"net/http"
	"os"
)

func main() {
	// Register http functions
	err1 := funcframework.RegisterHTTPFunctionContext(context.Background(), "/http1", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("HTTP Function 1 Called")
	})
	err2 := funcframework.RegisterHTTPFunctionContext(context.Background(), "/http2", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("HTTP Function 1 Called")
	})

	// Register an event functions
	err3 := funcframework.RegisterEventFunctionContext(context.Background(), "/event1", func(c context.Context, d interface{}) error {
		fmt.Println("Event Function 1 Called")
		return nil
	})
	err4 := funcframework.RegisterEventFunctionContext(context.Background(), "/event2", func(c context.Context, d interface{}) error {
		fmt.Println("Event Function 2 Called")
		return nil
	})

	// Check for errors
	fmt.Printf("Err1: %v, Err2: %v, Err3: %v, Err4: %v\n", err1, err2, err3, err4)

	// Use PORT environment variable, or default to 8080.
	port := "8080"
	if envPort := os.Getenv("PORT"); envPort != "" {
		port = envPort
	}

	// Start the cloud function framework and pass mux as the handler for incoming HTTP requests
	if err := funcframework.Start(port); err != nil {
		log.Fatalf("funcframework.Start: %v\n", err)
	}
}
```

No errors are returned when registering the functions.
I'm *not* using the environment variable `FUNCTION_TARGET`

I'm calling the test code with: `go run cmd/main/main.go`

Then I try to call each path using `curl`. For example:
```
curl http://127.0.0.1:8080/http1
```

This will return a 404 error message. And the same true for the the paths `/http1`, `/http2` and `/event1`

The only function which works is the final one, on the path `/event2`

I'm no Go expert, so it's very possible that I've miss-understood how the Framework is supposed to work. Or I'm doing something dumb.

Any advice would be appreciated, especially if it's to confirm that I'm not going crazy and that there could be an issue.

Thanks.
(I'm running this version of Go: `go version go1.19.3 darwin/amd64`)

**Comment by kevpie** [comment]
It looks like it was reverted just after the last release v1.6.1 was cut.
It has since been landed again.  
Try working with a more recent commit for instance... 
`v1.6.2-0.20221118004028-5b0ec7fed1e6`
v1.6.2 is not an actual tag yet but the date and and commit sha are used to pin a specific commit.

The version was generated when I tried to go get a commit
```sh
$ go get github.com/GoogleCloudPlatform/functions-framework-go@5b0ec7fed
go: downloading github.com/GoogleCloudPlatform/functions-framework-go v1.6.2-0.20221118004028-5b0ec7fed1e6
go: upgraded github.com/GoogleCloudPlatform/functions-framework-go v1.6.1 => v1.6.2-0.20221118004028-5b0ec7fed1e6
```

Then use a POST to call.
```sh
$ curl -X POST -d '{}' http://localhost:8080/http1
HTTP Function 1 Called
$ curl -X POST -d '{}' http://localhost:8080/event1
Event Function 1 Called
```

**Comment by gvmorley** [comment]
@kevpie 

That worked like a charm!

Thanks so much for getting me over that hump. It's much appreciated.
