### ISSUE TITLE
Issue: funcframework.Start: no matching function found with name

### ISSUE THREAD

**Issue by juanpabloguerra16** [GoogleCloudPlatform/functions-framework-go#167]
Hello, not sure if this is an issue or I have a problem on my code. But every time I try to change the env variable FUNCTION_TARGET, I get the error funcframework.Start: no matching function found with name "helloWorld"

main.go
```
package main

import (
	"log"
	"os"

	// Blank-import the function package so the init() runs
	_ "example.com/hello"
	"github.com/GoogleCloudPlatform/functions-framework-go/funcframework"
)

func main() {
	// Use PORT environment variable, or default to 8080.
	port := "8080"
	if envPort := os.Getenv("PORT"); envPort != "" {
		port = envPort
	}
	if err := funcframework.Start(port); err != nil {
		log.Fatalf("funcframework.Start: %v\n", err)
	}
}
```

function.go 

```
package function

import (
	"fmt"
	"net/http"

	"github.com/GoogleCloudPlatform/functions-framework-go/functions"
)

func init() {
	functions.HTTP("HelloWorld", helloWorld)
}

// helloWorld writes "Hello, World!" to the HTTP response.
func helloWorld(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "Hello, World!")
}
```

go.mod
```
module example.com/hello

go 1.18

require github.com/GoogleCloudPlatform/functions-framework-go v1.6.2-0.20221118004028-5b0ec7fed1e6

require (
	cloud.google.com/go/functions v1.0.0 // indirect
	github.com/cloudevents/sdk-go/v2 v2.6.1 // indirect
	github.com/google/uuid v1.1.2 // indirect
	github.com/json-iterator/go v1.1.10 // indirect
	github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421 // indirect
	github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742 // indirect
	go.uber.org/atomic v1.4.0 // indirect
	go.uber.org/multierr v1.1.0 // indirect
	go.uber.org/zap v1.10.0 // indirect
)
```

**Comment by paulsohops** [comment]
Is it just a case sensitivity issue? Your function is registering on `HelloWorld` but your error message has `helloWorld`. Try changing your `FUNCTION_TARGET` env variable to match the casing 🤞

**Comment by juanpabloguerra16** [comment]
no, I checked casing and it still happens. Thanks for your reply

**Comment by kenneth-rosario** [comment]
Can you show the output of ```echo $FUNCTION_TARGET```? 
Maybe ```export FUNCTION_TARGET=HelloWorld && go run main.go``` might do it

**Comment by josephlewis42** [comment]
We're closing this issue for now because we're waiting on follow-up. Please re-open it if you still need help.

Thanks!

**Comment by juanpabloguerra16** [comment]
when I run export FUNCTION_TARGET=HelloWorld && go run main.go it works but when I try changing my function name to Hello (removing World) it doesn't work. Somehow the function framework is not allowing me to change the name even after updating the function invocation and the env variable.

**Comment by juanpabloguerra16** [comment]
FWIW here's the output:
echo $FUNCTION_TARGET
Hello

if I run:
export FUNCTION_TARGET=Hello && go run cmd/main.go
Serving function: "Hello"2023/03/05 22:35:59 funcframework.Start: no matching function found with name: "Hello"
exit status 1
