### ISSUE TITLE
How to deploy multiple handlers in single Cloud Run Function?

### ISSUE THREAD

**Issue by zacharysyoung** [GoogleCloudPlatform/functions-framework-go#254]
I've been trying to follow along with how to use the framework to define multiple handlers, and got it working locally, but cannot get past having to define a single **Entry point** in the Deploy/Edit UI for Cloud Run Functions:

**function.go**

```go
func init() {
	...
	functions.HTTP("gen", genPDF)
	functions.HTTP("download", downloadPDF)
}

func genPDF(w http.ResponseWriter, r *http.Request) { ... }
func downloadPDF(w http.ResponseWriter, r *http.Request) { ... }
```

**./cmd/main.go**

```go
import (
	...

	_ "github.com/zacharysyoung/Workflow-Demo" // force init()

	"github.com/GoogleCloudPlatform/functions-framework-go/funcframework"
)

func main() {
	...
	if err := funcframework.StartHostPort("localhost", "8889"); err != nil {
		log.Fatalf("funcframework.StartHostPort: %v\n", err)
	}
}
```

That works fine when I run main.go, locally.

But when I try to deploy function.go (with a ZIP upload) the UI forces me to pick an **Entry point**, and I cannot leave that blank. If I pick either of genPDF or downloadPDF then the HTTPS trigger only calls that handler. I tried "/" on a whim, but that resulted in a broken deployment.

I've read through #172 and understand that this should be possible, but it doesn't mention how to make Cloud Function work with this scheme.

How do I configure the Cloud Function (through the UI) and/or the functions-framework so that the functions-framework to do its thang?

**Comment by chujchen** [comment]
Did you specify FUNCTION_TARGET as env var when you tested locally?

**Comment by zacharysyoung** [comment]
No, I didn’t need to; it just worked “out of the box”.On Dec 2, 2024, at 15:46, chujchen ***@***.***> wrote:﻿
Did you specify FUNCTION_TARGET as env var when you tested locally?

**Comment by chujchen** [comment]
Since UI is forcing single entrypoint, I don't think you can get away from it. One way to work around is specifying your path detection logic inside of one entrypoint function. 

```
func init() {
   functions.HTTP("HelloHTTP", helloHTTP)
}

// helloHTTP is an HTTP Cloud Function with a request parameter.
func helloHTTP(w http.ResponseWriter, r *http.Request) {
    // Get the requested URL path
	path := r.URL.Path

	// Route based on the path
	switch path {
	case "/hello":
		fmt.Fprintf(w, "Hello from the /hello path!")
	case "/goodbye":
		fmt.Fprintf(w, "Goodbye from the /goodbye path!")
	default:
		http.Error(w, "Path not found", http.StatusNotFound)
	}
}

```

**Comment by zacharysyoung** [comment]
@chujchen, thank you for taking a look at this.

Then, I'm still stuck trying to figure out what the thrust of #172 is. My interpretation is as follows:

1. OP asks:
   > Or do I have to deploy a separate Cloud Run function for every path?
2. a-h (Adrian Hesketh) says it appears to be a bug, the repository tags aren't up to date, but that it should work as OP (and me? expect) in an untagged commit, but they haven't actually tested it
3. josephlewis42 comments that the tags are up-to-date, and that they've verified the latest tags "supports multiple endpoints"

Which left me believing that "supports multiple endpoints" related to OP's original question of deploying in Cloud Function... but, maybe josephlewis42 was only confirming that multiple endpoints work [locally].

I think most of the pain of my issue (and maybe #172) is a lack of formal documentation, and trying to cobble information from issues and PRs.

Thanks again to all who looked into this.

**Comment by chujchen** [comment]
SG. Noted that deploying to Cloud run VS deploying to Cloud run function(or just Cloud function) is slightly different. If you are deploying to Cloud run, you are free to build function framework together with your function code(with multiple handlers) as an image and deploy it directly.  When it comes back to Cloud function, I don't think we have ever discussed whether we should support it officially as a feature. I will bring this up to the team. If we ever want to support it, we need to make sure it works for all runtimes, not just go. That's also something that needs to be double checked.
