### ISSUE TITLE
Question -> cloud event support could possibly break the API during CF update

### ISSUE THREAD

**Issue by lwsanty** [GoogleCloudPlatform/functions-framework-go#30]
First of all sorry for a confusing question, but we experience a weird behavior during using terraform since yesterday https://github.com/terraform-providers/terraform-provider-google/issues/6662

What happens is that terraform uses gcp api to update the cloud function that is triggered by pub sub, however during the build there's an error referencing to the wrong function handler signature: unexpectedly it requires http handler
```hcl
Error: Error waiting for Updating CloudFunctions Function: Error code 3, message: Build failed: # serverless_function_app/main
src/serverless_function_app/main/main.go:24:38: cannot use metadata.SlackNotifyFunc (type func(context.Context, *pubsub.Message) error) as type func(http.ResponseWriter, *http.Request) in argument to funcframework.RegisterHTTPFunction; Error ID: 6191efcd
  on main.tf line 595, in resource "google_cloudfunctions_function" "slack_notify":
 595: resource "google_cloudfunctions_function" "slack_notify" {
```
googling this error and ` funcframework.RegisterHTTPFunction` led us to this repo.

**Question** Is there any chance that this PR https://github.com/GoogleCloudPlatform/functions-framework-go/pull/29 could have an aforementioned impact on that build error? If yes, how can we fix it from the api caller side? If not, could you please suggest us any other directions to investigate?

Thank you.

**Comment by juliehockett** [comment]
Yes, that PR would cause that error, as it includes a breaking change to the registration functions. However, it has not been released at this point, and therefore is not supported on Google Cloud Functions as of yet. It will be available in the coming weeks as `v2.0.0`, but requires additional changes to both the framework and the backend to support fully.

Please verify that if you (or possibly, Terraform) include the Functions Framework in your dependencies provided with the deployment, it must be a released version of the framework. The latest released version is currently `v1.0.1`.

If neither you nor Terraform is pinning the framework version or you already pin `v1.0.1` or earlier, please file a bug against Cloud Functions for triage and investigation (https://cloud.google.com/functions/docs/getting-support#file_bugs_or_feature_requests).

**Comment by lwsanty** [comment]
@juliehockett thank you for a fast reply!
seems like they already have a similar issue https://issuetracker.google.com/issues/159608139

**Comment by michaelneale** [comment]
Minimal repository to reproduce issue: https://github.com/michaelneale/func-deploy-failure

**Comment by michaelneale** [comment]
@juliehockett I have tried pinning the version to no avail with vendoring (in my above example)

**Comment by lwsanty** [comment]
@juliehockett @michaelneale indeed pinning works, thank you!
however it is still a question for me why does it fail with the initial case.
