### ISSUE TITLE
Publish the recent CloudEvent support

### ISSUE THREAD

**Issue by cooperneil** [GoogleCloudPlatform/functions-framework-go#31]
Looks like the new cloudevent type support has not been published:
https://travis-ci.com/github/GoogleCloudPlatform/functions-framework-go/branches

was able to get a sample with a local main working by doing a `go get -u github.com/GoogleCloudPlatform/functions-framework-go@master`

Otherwise the error is:
./main.go:13:9: undefined: funcframework.RegisterCloudEventFunction

**Comment by grant** [comment]
CC @juliehockett

**Comment by grant** [comment]
@juliehockett  we can close with https://github.com/GoogleCloudPlatform/functions-framework-go/pull/36 right?
