### ISSUE TITLE
RegisterEventFunction data is empty

### ISSUE THREAD

**Issue by DeroSavage** [GoogleCloudPlatform/functions-framework-go#33]
Hey,

im trying to get a local test system running using the RegisterEventFunction function. In my pubsub emulator i configured a subscription using push to..push..the event data to the endpoint which is my go function. However this connection works but the event data is empty in my go program. Probably this doesn't work with push subscription, since in gcloud you don't even need to create a subscription, to use pubsub as a trigger right? 

```
// PubSubMessage is the payload of a Pub/Sub event. Please refer to the docs for
// additional information regarding Pub/Sub events.
type PubSubMessage struct {
	Data []byte `json:"data"`
}

// HelloPubSub consumes a Pub/Sub message.
func HelloPubSub(ctx context.Context, m PubSubMessage) error {
	log.Println(m)
	return nil
}
```

This is my code for "receiving" the pubsub message.

```
func main() {
	funcframework.RegisterEventFunction("/", generator.HelloPubSub)
	port := "8181"
	if envPort := os.Getenv("PORT"); envPort != "" {
		port = envPort
	}

	if err := funcframework.Start(port); err != nil {
		log.Fatalf("funcframework.Start: %v\n", err)
	}
}
```

And this just copied from the example, except the port.

**Comment by DeroSavage** [comment]
Update:

```

type PubSubMessage struct {
	Message struct {
		Data string `json:"data"`
	}
}

// HelloPubSub consumes a Pub/Sub message.
func HelloPubSub(ctx context.Context, m PubSubMessage) error {
	sDec, _ := base64.StdEncoding.DecodeString(m.Message.Data)
	fmt.Println(string(sDec))
	return nil
}
```
This returns the values i want. But that can't be the case or? Its encoded in base64, this happens somewhere on the way the event takes.

**Comment by juliehockett** [comment]
I believe the event may come in as base64 encoded -- the pubsub emulator unfortuantely does not precisely match what Cloud Functions gives you, and so I wouldn't be surprised if that's the case. I'm going to close this as WAI, please reopen if you run into further issues!
