### ISSUE TITLE
docs: add instructions on deploying via docker

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/functions-framework-go#35]
Current instructions in the README focus on using the framework locally and does not cover how to use the framework in the context of a docker container, something needed to deploy to services such as Cloud Run.

Add these instructions (primarily an example Dockerfile), for symmetry with https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/docker.md

```Dockerfile
FROM golang:1.14-buster as builder
WORKDIR /app
COPY . ./
RUN go build -mod=vendor -v -o server ./cmd

FROM debian:buster-slim
RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/server /app/server
CMD ["/app/server"]
```

This assumes the developer has already vendored dependencies to optimize build time. The key instruction is in the build command, targeting the `./cmd` directory.

**Comment by grant** [comment]
We may want to consistently add example Dockerfiles for all our function frameworks.

...and add docs about using Buildpacks consistently.

**Comment by grant** [comment]
We now have instructions here:

https://github.com/GoogleCloudPlatform/functions-framework-go#go-further-build-a-deployable-container

**Comment by grant** [comment]
Per above (https://github.com/GoogleCloudPlatform/functions-framework-go/pull/41) and some other PRs, we now have instructions for building a container via buildpacks and running those in each functions framework.

These [buildpacks](https://github.com/GoogleCloudPlatform/buildpacks) are the ones we officially maintain and use with GCF, so they're a bit better than a Dockerfile.

---

Also related: I also have published a few blogposts about deploying to Cloud Run in various languages: https://medium.com/@granttimmerman
