### ISSUE TITLE
Support for Receiving Messages From PubSub Emulator?

### ISSUE THREAD

**Issue by aventurella** [GoogleCloudPlatform/functions-framework-go#46]
Maybe I just have things setup improperly, but it appears that a request from the PubSub emulator is not formatted in a way that the function framework handles?

For example, if I send a JSON Payload as:

```json
{
    "data":"<base64 encoded>"
}
```

The functions framework will do the right thing and all is well.  However when I set a PubSub Emulator Subscription endpoint things are not well:

Those payloads come across the wire shaped like this:

```json
{
      "subscription": "projects/local-project/subscriptions/local-test",
      "message": {
        "data": "<base64 string>",
        "messageId": "7",
        "attributes": {
          "key": "value"
        }
    }
}
```

Note the `message` is embedded in an object envelope.

Is there a way to have the functions framework when registering the function with:

```go
funcframework.RegisterEventFunctionContext(ctx, "/", action)
```

handle these types of requests?

**Comment by grant** [comment]
Sorry about not commenting on this earlier.

There are known issues with the beta Pub/Sub emulator with the Function Frameworks.
I personally like to use cURL to test my functions – we have docs coming out soon on that.

---

We also have docs here for testing Pub/Sub functions:

https://cloud.google.com/functions/docs/testing/test-background
