### ISSUE TITLE
[Feature request] Support hot-reloading

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/functions-framework-go#48]
Hi Team,

Would it be possible to support hot-reloading, when serving locally and function code is modified (i.e. without having to restart the server)? And are other any existing workarounds to enable this currently (I'm thinking to do something through `fswatch`)?

Thanks!

**Comment by grant** [comment]
Hey @dinvlad, I'm not sure of the exact solution.

I don't think Golang makes it possible to inject code without having to restart the server. Go is a compiled language, so we need to compile the code before running the server. Not sure if Go has a way to inject changes.

Was looking at some blogposts:
https://medium.com/@jeyraj/live-reload-for-go-afef9c25420a

If you're ok with restarting the server, I think that would be much easier.
Maybe use a tool like https://github.com/Unknwon/bra?

**Comment by dinvlad** [comment]
Thanks @grant - makes sense, and I was actually looking at external tools as well last night, as there're plenty:
https://techinscribed.com/5-ways-to-live-reloading-go-applications/
https://dev.to/gcdcoder/using-live-reload-in-go-48l3

So I think I'll Go with one of those :)

**Comment by grant** [comment]
Cool. Let us know if one of those solutions work and we can possibly link it here or write a blog post about it.

Going to close this, but feel free to comment or ask for me to reopen if there's a suggested change to this repo 🙂
