### ISSUE TITLE
Distributed tracing causing issues with Google Cloud Function deploy

### ISSUE THREAD

**Issue by RobinUS2** [GoogleCloudPlatform/functions-framework-go#56]
as of today we tried to redeploy an existing function (no changes actually, so quite odd) with the following error:
```
Deploying function (may take a while - up to 2 minutes)...
..
For Cloud Build Stackdriver Logs, visit: https://console.cloud.google.com/logs/viewer?project=SNIP&advancedFilter=resource.type%3Dbuild%0Aresource.labels.build_id%3D11fd0f83-01ca-SNIP-2de2857b7199%0AlogName%3Dprojects%2FSNIP%2Flogs%2Fcloudbuild
..................................................failed.
ERROR: (gcloud.functions.deploy) OperationError:
 code=3, message=Build failed: # github.com/cloudevents/sdk-go/v2/extensions
src/github.com/cloudevents/sdk-go/v2/extensions/distributed_tracing_extension.go:161:3: cannot use span (type trace.Span) as type *trace.Span in return argument:
	*trace.Span is pointer to interface, not interface; Error ID: 1093f764 
FATA[0136] failed deployment of 383: exit status 1   
```

screenshot of cloud build logs:
<img width="1397" alt="Screenshot 2020-10-23 at 14 52 44" src="https://user-images.githubusercontent.com/1712500/97006037-8b5a3580-153f-11eb-8595-0f8099059ee9.png">

other people referencing the same issue:
- https://github.com/cloudevents/sdk-go/issues/601

**Comment by tbpg** [comment]
Thank you for the report. We're investigating and working on a fix.

**Comment by ottob** [comment]
Deploying works again now. Thanks for a quick fix.

**Comment by tbpg** [comment]
Great. I'm seeing the same thing on my side.

**Comment by tbpg** [comment]
Closing this, but let us know if it comes up again!
