### ISSUE TITLE
Expand the CloudEvent function signatures to support reply

### ISSUE THREAD

**Issue by mattmoor** [GoogleCloudPlatform/functions-framework-go#58]
The Knative Broker supports replying to events with a new event that is enqueued onto the Broker.

The Cloud Event SDK already supports a fairly extensive collection of signatures ([source](https://godoc.org/github.com/cloudevents/sdk-go/v2/client#Client)):
```
    // Valid fn signatures are:
    // * func()
    // * func() error
    // * func(context.Context)
    // * func(context.Context) protocol.Result
    // * func(event.Event)
    // * func(event.Event) protocol.Result
    // * func(context.Context, event.Event)
    // * func(context.Context, event.Event) protocol.Result
    // * func(event.Event) *event.Event
    // * func(event.Event) (*event.Event, protocol.Result)
    // * func(context.Context, event.Event) *event.Event
    // * func(context.Context, event.Event) (*event.Event, protocol.Result)
```

Which are supported by the method y'all are already calling to set everything up:
https://github.com/GoogleCloudPlatform/functions-framework-go/blob/fed357741a8521eeeaad9b32dc140d69ea69626c/funcframework/framework.go#L147

I believe the only functional changes to make this work are changing the signatures here:
https://github.com/GoogleCloudPlatform/functions-framework-go/blob/fed357741a8521eeeaad9b32dc140d69ea69626c/funcframework/framework.go#L141

... and here:
https://github.com/GoogleCloudPlatform/functions-framework-go/blob/fed357741a8521eeeaad9b32dc140d69ea69626c/funcframework/framework.go#L95

... to accept `interface{}` (the same way `RegisterHTTPFunction` and `RegisterEventFunction` already do).

If y'all would be receptive to this change, I'd be happy to send a PR with the above, some doc updates, and tests?

cc @squee1945

**Comment by mattmoor** [comment]
Just as a datapoint, this is what the Boson (Red Hat) function signature, which also uses buildpacks is doing here: https://github.com/boson-project/faas/blob/e8b622e1aabc3d154c12e9486b36b2c4b7d3e316/templates/go/events/handle.go#L25

**Comment by squee1945** [comment]
Are you suggesting that the Function Framework would somehow dispatch this returned event?

**Comment by mattmoor** [comment]
In the Knative Broker model, the invoked service simply replies with it via the HTTP response, and the Broker re-enqueues it. 
 So my expectation with this would be that if a function returned an event it was simply returned to the caller via an HTTP response.

For example, using the "binary" form of CloudEvents this would look like:
```
...
Content-Type: application/json
CE-Type: dev.mattmoor.foo.bar
CE-Source: ...
CE-ID: ...
CE-I-FORGET: ...

{
  "a": 1,
  "b": 2
}
```

This is simply one interpretation of the receiver contract, but with the HTTP receiver (that y'all are using), this is the natural interpretation.

**Comment by mattmoor** [comment]
I optimistically sent: https://github.com/GoogleCloudPlatform/functions-framework-go/pull/61

Hopefully the new test paints the picture for what I mean a bit better.  Effectively, when you reply with a `cloudevents.Event` is becomes the HTTP response.
