### ISSUE TITLE
deploying to us-west2 fails

### ISSUE THREAD

**Issue by al-bglhk** [GoogleCloudPlatform/functions-framework-go#74]
I tried to deploy a function to `us-west2` region and I always get the following error
```
ERROR: (gcloud.alpha.functions.deploy) OperationError: code=3, message=Build failed: vendored dependencies must include "github.com/GoogleCloudPlatform/functions-framework-go"; if your function does not depend on the module, please add a blank import: `_ "github.com/GoogleCloudPlatform/functions-framework-go"`; Error ID: fd86168a
```

which is strange, because 

1. It never happened before. My last successful deployment was at Aug 26. 
2. In the docs, it says that library is automatically installed when deploying. https://cloud.google.com/functions/docs/running/function-frameworks
3. When I tried to follow the message, i.e. installing and importing the package as `_`, I get 
```
ERROR: (gcloud.alpha.functions.deploy) OperationError: code=3, message=Build failed: can't load package: package functions.local/app: cannot find module providing package functions.local/app; Error ID: 1a663392
```
at which point, I gave up.

One more thing to note is, when I deploy the same function `europe-west3`, it doesn't fail.

**Comment by al-bglhk** [comment]
Seems to be fixed https://status.cloud.google.com/incidents/5yL8cbrpS3ssbYjRZQJv

**Comment by grant** [comment]
Thanks for the issue.

We don't really triage issues with Cloud Functions here, but the best way to file issues is here:
https://cloud.google.com/functions/docs/support
